import { useEffect } from "react";
const THEMES = {
  dark: {
    primary: '#A78BFA',
    secondary: '#0B1019',
    accent: '#1D4ED8',
    background: '#0E1118',
    surface: '#151B26',
    elevated: '#1C2332',
    textPrimary: '#E5E9F2',
    textSecondary: '#A7B3C6',
    textTertiary: '#7B8499',
    border: '#242C3A',
    divider: '#1B2230',
    success: '#35C48D',
    warning: '#F0C35B',
    error: '#EE6D7A',
    info: '#6CB6FF',
    hover: '#3A4A66',
    disabled: '#3A3F4D',
    textInfo: "Dark theme tuned for soft contrast, clear hierarchy, and comfortable reading.",
  },
  cappuccino: {
    primary: '#704F34',
    secondary: '#EDE5D9',
    accent: '#C17A4F',
    background: '#FAF8F4',
    surface: '#F3EFEA',
    elevated: '#EBE5DE',
    textPrimary: '#2D1F15',
    textSecondary: '#5C4A3D',
    textTertiary: '#8B7765',
    border: '#D9CFC4',
    divider: '#E5DCC9',
    success: '#059669',
    warning: '#D97706',
    error: '#DC2626',
    info: '#0284C7',
    hover: '#E0D5C7',
    disabled: '#C4B5A0',
    textInfo: "A warm cream theme with excellent contrast for readability.",
  },
  // Light (CLAIRE)
  'cottage-core': {
    primary: '#A5715E',
    secondary: '#F0E8DC',
    accent: '#7BAA6F',
    background: '#FAF7F2',
    surface: '#F3EEE6',
    elevated: '#ECE6DE',
    textPrimary: '#2C2A26',
    textSecondary: '#60584F',
    textTertiary: '#9A9186',
    border: '#DCD4C8',
    divider: '#E6DFD5',
    success: '#2E8B57',
    warning: '#C0853F',
    error: '#C44949',
    info: '#3F82A8',
    hover: '#E9E3DA',
    disabled: '#C8C0B6',
    textInfo: 'Warm natural palette evoking cottage comfort.'
  },
  'quenya': {
    primary: '#7CC2A1',
    secondary: '#E7EFEB',
    accent: '#3BA38E',
    background: '#F4F8F6',
    surface: '#EEF4F1',
    elevated: '#E7EFEB',
    textPrimary: '#1F2A27',
    textSecondary: '#53645E',
    textTertiary: '#7F948D',
    border: '#D1DED8',
    divider: '#E0EBE6',
    success: '#2BAE66',
    warning: '#C9983A',
    error: '#C45E5E',
    info: '#3A86C8',
    hover: '#E6EFEA',
    disabled: '#C7D5CF',
    textInfo: 'Elven clarity with mint and emerald accents.'
  },
  'valinor': {
    primary: '#D9A441',
    secondary: '#F0E8D7',
    accent: '#8B6B2E',
    background: '#FCFAF3',
    surface: '#F6F0DF',
    elevated: '#EFE7CC',
    textPrimary: '#2E2818',
    textSecondary: '#6A604D',
    textTertiary: '#978C77',
    border: '#E3DAC4',
    divider: '#EEE6D3',
    success: '#3F9D6C',
    warning: '#CE8F2A',
    error: '#C7534D',
    info: '#6C8DBB',
    hover: '#F0E8D7',
    disabled: '#CEC5B1',
    textInfo: 'Golden light of the West, soft and readable.'
  },
  'magical-doremi': {
    primary: '#F49AC2',
    secondary: '#F3E5F2',
    accent: '#B78AF0',
    background: '#FFF6FB',
    surface: '#FCECF6',
    elevated: '#F5E2F0',
    textPrimary: '#3A2935',
    textSecondary: '#6F5A69',
    textTertiary: '#9B8796',
    border: '#EAD5E6',
    divider: '#F2DFED',
    success: '#48C78E',
    warning: '#F0B557',
    error: '#E6757D',
    info: '#8AB9F7',
    hover: '#F3E5F2',
    disabled: '#D7C7D4',
    textInfo: 'Pastel magic with high readability.'
  },
  'crystal-clear': {
    primary: '#73B3FF',
    secondary: '#EAF3FA',
    accent: '#3FA7E0',
    background: '#F7FBFF',
    surface: '#F0F7FD',
    elevated: '#E7F2FB',
    textPrimary: '#1E2A33',
    textSecondary: '#5A6C79',
    textTertiary: '#8A9AA6',
    border: '#D5E3F0',
    divider: '#E3EEF7',
    success: '#2EA36A',
    warning: '#D2993B',
    error: '#D14646',
    info: '#3BA1D6',
    hover: '#EAF3FA',
    disabled: '#C9DAE8',
    textInfo: 'Icy clarity with crisp contrast.'
  },
  // Dark (Obscure)
  'murasaki-synthwave': {
    primary: '#BB86FC',
    secondary: '#151424',
    accent: '#00D1FF',
    background: '#0B0A12',
    surface: '#151424',
    elevated: '#1D1B2E',
    textPrimary: '#ECEAF7',
    textSecondary: '#A6A1C9',
    textTertiary: '#7E77A8',
    border: '#2A2740',
    divider: '#1E1C30',
    success: '#34D399',
    warning: '#F59E0B',
    error: '#F87171',
    info: '#60A5FA',
    hover: '#231F3A',
    disabled: '#3A3656',
    textInfo: 'Neon purple and cyan on deep night.'
  },
  'cyberpunk': {
    primary: '#FF00A8',
    secondary: '#171A21',
    accent: '#00E5FF',
    background: '#0D0F13',
    surface: '#171A21',
    elevated: '#1F232C',
    textPrimary: '#E8F1FF',
    textSecondary: '#99A4B3',
    textTertiary: '#778293',
    border: '#2A313D',
    divider: '#1B212A',
    success: '#22C55E',
    warning: '#F6AD55',
    error: '#EF4444',
    info: '#38BDF8',
    hover: '#232833',
    disabled: '#3A4350',
    textInfo: 'Neon accents with crisp readability.'
  },
  'fruity-loop': {
    primary: '#72E06C',
    secondary: '#1A1A1A',
    accent: '#FF7A00',
    background: '#121212',
    surface: '#1A1A1A',
    elevated: '#202020',
    textPrimary: '#EDEDED',
    textSecondary: '#A7A7A7',
    textTertiary: '#8C8C8C',
    border: '#2B2B2B',
    divider: '#1E1E1E',
    success: '#72E06C',
    warning: '#F0B429',
    error: '#E64A4A',
    info: '#5AA7FF',
    hover: '#262626',
    disabled: '#3B3B3B',
    textInfo: 'FL Studio-inspired dark with orange accents.'
  },
  'dominate': {
    primary: '#E53935',
    secondary: '#17171B',
    accent: '#FF6F61',
    background: '#0E0E10',
    surface: '#17171B',
    elevated: '#1F2026',
    textPrimary: '#F0F2F5',
    textSecondary: '#A8ABB2',
    textTertiary: '#8D9096',
    border: '#2A2C33',
    divider: '#1B1C22',
    success: '#3CCF7A',
    warning: '#F4B23D',
    error: '#FF5A5A',
    info: '#6EB6FF',
    hover: '#23242B',
    disabled: '#3A3C43',
    textInfo: 'Bold red accents with strong contrast.'
  },
  'expedition33': {
    primary: '#89B4D8',
    secondary: '#161C22',
    accent: '#3D8FB3',
    background: '#0F1418',
    surface: '#161C22',
    elevated: '#1D242C',
    textPrimary: '#E6EBF1',
    textSecondary: '#A7B0BB',
    textTertiary: '#8793A0',
    border: '#26303A',
    divider: '#1B252E',
    success: '#44C089',
    warning: '#D69E2E',
    error: '#E76E66',
    info: '#5DA8E3',
    hover: '#222A33',
    disabled: '#3A424C',
    textInfo: 'Adventure-inspired cool stone palette.'
  },
  'duality-fee9fc-e1e1e1': {
    primary: '#B76BA3',
    secondary: '#E1E1E1',
    accent: '#7A7A7A',
    background: '#EDEDED',
    surface: '#FEE9FC',
    elevated: '#F6DFF3',
    textPrimary: '#262626',
    textSecondary: '#5E5E5E',
    textTertiary: '#8E8E8E',
    border: '#D8D8D8',
    divider: '#E6E6E6',
    success: '#2EA36A',
    warning: '#D2993B',
    error: '#D14646',
    info: '#3BA1D6',
    hover: '#F5F0F6',
    disabled: '#C9C9C9',
    textInfo: 'Playful duality of pink and gray.'
  },
  'rune': {
    primary: '#D4A373',
    secondary: '#1A1D1F',
    accent: '#9D6A3D',
    background: '#111314',
    surface: '#1A1D1F',
    elevated: '#202427',
    textPrimary: '#E7ECEF',
    textSecondary: '#A3ADB8',
    textTertiary: '#88929D',
    border: '#2A2F34',
    divider: '#1B2024',
    success: '#58B38C',
    warning: '#CE9B3B',
    error: '#D66B6B',
    info: '#7FA7C3',
    hover: '#24282C',
    disabled: '#3A4046',
    textInfo: 'Ancient stone with amber accents.'
  },
  // Colorful
  'kawaii': {
    primary: '#BFA6FF',
    secondary: '#FFEFF6',
    accent: '#FF85B3',
    background: '#FFF7FB',
    surface: '#FFEFF6',
    elevated: '#FFE6F1',
    textPrimary: '#3A2A36',
    textSecondary: '#6E586A',
    textTertiary: '#988497',
    border: '#F2D6E5',
    divider: '#F7DFEC',
    success: '#48C78E',
    warning: '#F0B557',
    error: '#E6757D',
    info: '#8AB9F7',
    hover: '#F7E8F0',
    disabled: '#DBC9D3',
    textInfo: 'Pastel candy with strong legibility.'
  },
  'shingeki': {
    primary: '#8D5E3C',
    secondary: '#EEE6D4',
    accent: '#3A5A40',
    background: '#F5EFE2',
    surface: '#EEE6D4',
    elevated: '#E6DDC8',
    textPrimary: '#2A2A24',
    textSecondary: '#5B5B50',
    textTertiary: '#8A8A7C',
    border: '#D9CFBD',
    divider: '#E7DECC',
    success: '#2F7D4D',
    warning: '#C48A2B',
    error: '#B0473C',
    info: '#597A9B',
    hover: '#EDE3D2',
    disabled: '#C9C0AE',
    textInfo: 'AoT-inspired parchment and military green.'
  },
  'esquie': {
    primary: '#7FB3D5',
    secondary: '#ECF3F8',
    accent: '#5BC0EB',
    background: '#F3F7FA',
    surface: '#ECF3F8',
    elevated: '#E4EEF5',
    textPrimary: '#1E2730',
    textSecondary: '#566273',
    textTertiary: '#8593A3',
    border: '#D2DEE8',
    divider: '#E1EAF1',
    success: '#28A985',
    warning: '#D39A2E',
    error: '#D14F4F',
    info: '#4AA8D8',
    hover: '#E7F0F6',
    disabled: '#C6D3DF',
    textInfo: 'Expedition33-inspired airy azure.'
  },
};

export const useTheme = (themeName: string, customTheme?: any) => {
  useEffect(() => {
    const theme =
      themeName === "custom" && customTheme
        ? customTheme
        : THEMES[themeName as keyof typeof THEMES] || THEMES.dark;
    const root = document.documentElement;
    root.style.setProperty("--primary", theme.primary);
    root.style.setProperty("--secondary", theme.secondary);
    root.style.setProperty("--accent", theme.accent);
    root.style.setProperty("--background", theme.background);
    root.style.setProperty("--surface", theme.surface);
    root.style.setProperty("--elevated", theme.elevated);
    root.style.setProperty("--text-primary", theme.textPrimary);
    root.style.setProperty("--text-secondary", theme.textSecondary);
    root.style.setProperty("--text-tertiary", theme.textTertiary);
    root.style.setProperty("--border", theme.border);
    root.style.setProperty("--divider", theme.divider);
    root.style.setProperty("--success", theme.success);
    root.style.setProperty("--warning", theme.warning);
    root.style.setProperty("--error", theme.error);
    root.style.setProperty("--info", theme.info);
    root.style.setProperty("--hover", theme.hover);
    root.style.setProperty("--disabled", theme.disabled);
  }, [themeName, customTheme]);
};
